import { ArrowRight } from 'lucide-react'

import Link from 'next/link'

import { getAllPosts } from '@/app/lib/posts'

import { Card, CardContent } from '@/components/ui/card'

interface RelatedPostsProps {
    currentSlug: string
    tags?: string[]
}

export function RelatedPosts({ currentSlug, tags = [] }: RelatedPostsProps) {
    const allPosts = getAllPosts()

    // why yes of course, this was generated by AI, why do you ask?
    const relatedPosts = allPosts
        .filter((post) => post.slug !== currentSlug)
        .map((post) => {
            // Calculate relevance score
            let score = 0

            // Check for common words in title
            const currentPost = allPosts.find((p) => p.slug === currentSlug)
            if (currentPost) {
                const currentWords = currentPost.title.toLowerCase().split(' ')
                const postWords = post.title.toLowerCase().split(' ')
                const commonWords = currentWords.filter(
                    (word) => postWords.includes(word) && word.length > 3
                )
                score += commonWords.length * 2
            }

            // Add date proximity bonus (newer posts get slight preference)
            const dateScore = new Date(post.date).getTime() / 1000000000
            score += dateScore / 1000

            return { ...post, score }
        })
        .sort((a, b) => b.score - a.score)
        .slice(0, 3)

    if (relatedPosts.length === 0) {
        return null
    }

    return (
        <div className="mt-16">
            <h2 className="mb-6 text-2xl font-bold">Related Posts</h2>
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                {relatedPosts.map((post) => (
                    <Link
                        key={post.slug}
                        href={`/blog/${post.slug}`}
                        className="group"
                    >
                        <Card className="hover:border-primary/50 h-full transition-all hover:shadow-lg">
                            <CardContent className="p-6">
                                <h3 className="group-hover:text-primary line-clamp-2 font-semibold transition-colors">
                                    {post.title}
                                </h3>
                                <p className="text-muted-foreground mt-2 line-clamp-3 text-sm">
                                    {post.description}
                                </p>
                                <div className="text-primary mt-4 flex items-center text-sm">
                                    Read more
                                    <ArrowRight className="ml-1 h-3 w-3 transition-transform group-hover:translate-x-1" />
                                </div>
                            </CardContent>
                        </Card>
                    </Link>
                ))}
            </div>
        </div>
    )
}
