import { formatMonthYear } from '@/lib/format'
import { getAllPosts } from '@/lib/posts'

import { ListRow, ListRows } from '@/components/list-row'
import { Eyebrow } from '@/components/section'

interface RelatedPostsProps {
    currentSlug: string
}

export function RelatedPosts({ currentSlug }: RelatedPostsProps) {
    const allPosts = getAllPosts()
    const currentPost = allPosts.find((post) => post.slug === currentSlug)

    // why yes of course, this was generated by AI, why do you ask?
    const relatedPosts = allPosts
        .filter((post) => post.slug !== currentSlug)
        .map((post) => {
            // Calculate relevance score
            let score = 0

            // Check for common words in title
            if (currentPost) {
                const currentWords = currentPost.title.toLowerCase().split(' ')
                const postWords = post.title.toLowerCase().split(' ')
                const commonWords = currentWords.filter(
                    (word) => postWords.includes(word) && word.length > 3
                )
                score += commonWords.length * 2
            }

            // Add date proximity bonus (newer posts get slight preference)
            const dateScore = new Date(post.date).getTime() / 1000000000
            score += dateScore / 1000

            return { ...post, score }
        })
        .sort((a, b) => b.score - a.score)
        .slice(0, 3)

    if (relatedPosts.length === 0) {
        return null
    }

    return (
        <div className="border-border border-t pt-8">
            <Eyebrow>More writing</Eyebrow>
            <ListRows>
                {relatedPosts.map((post) => (
                    <ListRow
                        key={post.slug}
                        href={`/blog/${post.slug}`}
                        title={post.title}
                        meta={formatMonthYear(post.date)}
                        variant="compact"
                    />
                ))}
            </ListRows>
        </div>
    )
}
